config/routes.rb
Members::Application.routes.draw do
  mount RailsAdmin::Engine => '/backoffice', :as => 'rails_admin'

  devise_for :admins
  devise_for :members
  resources :members

  get 'statute_home', :to => 'home#statute'
  get 'change_participation', to: 'members#change_participation'

  root :to => "home#index"

end

app/models/admin.rb
# -*- encoding : utf-8 -*-
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/models/member.rb
# -*- encoding : utf-8 -*-
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :participate, :name, :address, :city, :postcode,:country, :email, :password, :password_confirmation, :remember_me

  validates :name,:email, :country, :city, :presence => true
  #validates :postcode, :presence => true, :numericality => true

  scope :members, where('sign_in_count > 0').order('participate DESC')
  scope :participants, where(:participate => true)



  def change_participation
    self.update_attribute(:participate, !self.participate)
  end


  def self.mass_invite(email_name_string)
    email_name_string.lines.reduce([]) do |members, line|
      email, name = line.split(',')
      raise "ugyldig format. både epost (#{email}) og navn (#{name}) må oppgis. Kontroller din input ved å trykke BACK knappen i nettleseren" if email.nil? || name.nil?
      email = email.chomp
      if Member.find_by_email(email)
         puts "member #{email} exists"
      else
        puts "inviting #{email}"
        members << {email: email, name: name.gsub('"','').chomp}
      end
      members
    end
  end

  def self.mass_invite!(email_name_string)
    mass_invite(email_name_string).each do |m|
      Member.invite!(m)
    end.count
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end

  def statute
  end
end

app/controllers/members_controller.rb
# -*- encoding : utf-8 -*-
class MembersController < ApplicationController
  USER_ACTIONS = [:show, :edit, :update, :destroy, :change_participation]
  before_filter :authenticate_admin!, except: USER_ACTIONS
  before_filter :authenticate_member!, only: USER_ACTIONS
  before_filter :set_host_from_request, only: [:create]

  # GET /members
  # GET /members.json
  def index
    @members = Member.members
    @participants = Member.participants
    @invited_count = Member.count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end


  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end



  # GET /members/new
  # GET /members/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /members
  # POST /members.json
  def create
    count = Member.mass_invite!(params["MassInvite"]["emails"])
    respond_to do |format|
      format.html { redirect_to new_member_path, notice: "Yaay! Totalt #{count} invitasjoner ble sendt." }
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])
    respond_to do |format|
      m = params[:member]
      if if m[:password].blank?                ### IF block returning bool
          @member.update_without_password(m)
        else
          @member.update_attributes(m)
          sign_in @member, :bypass => true
          true
        end                                     ### end IF block returning bool to outer if.
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  # GET /
  def change_participation
     current_member.change_participation
     respond_to do |format|
        format.html { redirect_to root_url }
     end
  end

  private
  def set_host_from_request
    ActionMailer::Base.default_url_options = { host: request.host_with_port }
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/views/common/_admin_menu.html.erb
<% if admin_signed_in?  %>
  <li><%= link_to('Medlemmer', members_path) %></li>
  <li><%= link_to('Backoffice', rails_admin_path) %></li>
  <li><%= link_to "Admin logg ut", destroy_admin_session_path, :method => :delete %> </li>
<% else  %>
  <li><%= link_to "Admin", new_admin_session_path %></li>
<% end  %>

app/views/common/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert alert-success">
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert alert-error">
    <%= content_tag :div, flash[:error] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert alert-info">
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

app/views/common/_member_menu.html.erb
<% if member_signed_in? %>
  <li><%= link_to('Logg ut', destroy_member_session_path, :method => :delete) %></li>
  <li><%= link_to 'Hei '+current_member.name+'!', '#' %></li>
<% else %>
  <li><%= link_to('Logg inn', new_member_session_path)  %></li>
<% end %>

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>Årsmøte </h1>

  <h3>Velkommen <%= member_signed_in? ? current_member.name: '' %>!</h3>
  <br/>
  <p>Smidigbevegelsens årlige hovedbegivenhet, smidigkonferansene, holder årsmøte <strong>22.mars 2012 kl 17:00 i 3.etg på Scotsman i Oslo</strong> (<a href="http://maps.google.no/maps?um=1&ie=UTF-8&q=scotsman+oslo&fb=1&gl=no&hq=scotsman&hnear=0x46416e61f267f039:0x7e92605fd3231e9a,Oslo&cid=0,0,11535085172773240985&ei=vyJnT6igO6aD4gTq6cHZBw&sa=X&oi=local_result&ct=image&ved=0CB0Q_BI">kart</a>) Kontaktperson Arne Løvold, tlf 91761465. Bli med på arrangørsamlingen som starter umiddelbart etter årsmøtet og vær med å forme fremtiden!
  Alle deltakere på Smidig2010 eller Smidig2011 inviteres også til å bli medlemmer av foreningen Smidigkonferansen.
    <% if member_signed_in? %>
       <p>Din status på deltakelse på årsmøtet (generalforsamlingen) og/eller arrangørkonferansen:
       </p>

  <div class="well">
        <% if current_member.participate  %>

  <p class="large">
              <span class="label label-success">JA</span> Du kommer.
</p>
          <p>
          <%= link_to "Endre til &raquo; Jeg kommer ikke".html_safe, change_participation_path, class: 'btn btn-danger btn-small' %>
        <% else %>
          <p>
            <span class="label label-important">NEI</span> Du kommer ikke.
          </p>
          <p>
          <%= link_to "Endre til &raquo; Jeg kommer!".html_safe, change_participation_path, class: "btn btn-primary btn-large" %>
        <% end %>
      <% end %>
</div>
</p>


</div>

<!-- Example row of columns -->
<div class="row">
  <div class="span4">
    <h2>Smidig2007  &raquo;</h2>

    <p> Første smidigkonferanse ble avholdt i 2007, som en nyskapende og annerledes konferanse. Det er fremdeles annerledes, men flere har tatt etter trenden med lyntaler (lightning talks). Open space er det fremdeles svært få som gjør.</p>
  </div>
  <div class="span4">
    <h2> Bla bla bla </h2>

    <p> Smidigkonferansene handler om erfaringsdeling, på godt norsk: prat! Konferansene har trukket tilsammen 2000 deltakere og 350 lyntaler siden 2007. <strong>Du</strong> kan være med gjøre en forskjell. Møt til arrangørkonferansen.</p>

  </div>
  <div class="span4">
    <h2> &raquo; Smidig2012</h2>

    <p>Konferansen er fremdeles annerledes, men er ikke særlig innovativ lenger. Ønsker du det? Kom på <strong>Arrangørkonferansen</strong> og få en mulighet til å forme fremtiden.</p>

    <!-- p><a class="btn" href="#">View details &raquo;</a></p -->
  </div>
</div>

<hr>

app/views/home/statute.html.erb
<h3>Vedtekter for Smidigkonferansen</h3>

<br />
<h4>§1 Navn og form</h4>

<p>Foreningens navn er "Smidigkonferansen". Foreningen er en frittstående, ikke-kommersiell interesseforening. Foreningen er selveiende, og disponerer over sin egen formue og sine egne midler.</p>
<p>Foreningen er uavhengig og har ingen kommersielle interesser, og må ikke engasjere seg i aktiviteter som utelukkende tjener økonomiske formål. Foreningen opptrer ikke som representant for noe selskap, yrkes- eller næringsgruppe til å fremme egne økonomiske interesser.</p>

<br />
<h4>§2 Formål</h4>

<p>Foreningens formål er å arrangere en årlig konferanse for IT-fagmiljøet i Norge.</p>

<br />
<h4>§3 Medlemskap</h4>

<p>Enhver som har deltatt på minst en av de siste to konferansene har rett til medlemskap i foreningen for ett år om gangen. Medlemskap må være registrert skriftlig 14 kalenderdager før årsmøtet for at medlemmet har stemmerett.</p>

<p>Deltagelse på konferansen gir ikke automatisk medlemskap.</p>

<p>Medlemmer har rett til å stille på årsmøte. Medlemmer har ingen forpliktelser.</p>

<br />
<h4>§4 Årsmøte</h4>

<p>Årsmøtet er foreningens øverste organ. Ordinært årsmøte holdes årlig i første kvartal. Årsmøtet innkalles med minst en kalendermåneds varsel per websider, e-post, eller på annen måte som når medlemmene. Saker til årsmøtet må være styret i hende senest to uker før årsmøtet. Full saksliste skalt framligge senest én uke før årsmøtet.</p>

<p>Følgende saker behandles:
<ul></li>
<li>Valg av møteleder og referent.</li>
<li>Godkjennelse av regnskap og årsberetning.</li>
<li>Gjennomgang av budsjett.</li>
<li>Valg av styre, valgkomité og revisor.</li>
<li>Vedtektsendringer.</li>
<li>Andre saker som er meldt inn til årsmøtet.</li>
</ul>
</p>

<p>Ekstraordinært årsmøte skal avholdes om styret, revisor eller minst en tredjedel av medlemmene krever det.</p>

<p>Alle saker avgjøres ved alminnelig flertall blant møtende medlemmer. Ved stemmelikhet er møteleders stemme avgjørende.</p>

<br />
<h4>§5.1 Styret</h4>

<p>Styret er ansvarlig for foreningens daglige virksomhet. Styret består av leder, minst 5 styremedlemmer og minst 2 varamedlemmer. Styret konstituerer seg selv. Leder og styrets medlemmer har 2 års funksjonstid, dog slik at henholdsvis 2 og 3 styremedlemmer er på valg hvert år. Varamedlemmenes funksjonstid er 1 år. Styreleder velges innad av styret hvert år</p>
<p>Varamedlemmer kan kalles inn til styremøter ved sykdom eller behov, samt delta innad i styrets korrespondanser. De har imidlertid kun stemmerett om de deltar i styremøtet i et styremedlems sted. </p>

<br />
<h4>§5.2 Styrets oppgaver:</h4>

<p><ul>
<li>Iverksette årsmøtets bestemmelser.</li>
<li>Forvalte og føre tilsyn med foreningens virksomhet.</li>
<li>Behandle budsjettering, løpende utgifter og regnskapsføring.</li>
<li>Behandle medlemskap.</li>
<li>Representere Smidigkonferansen utad.</li>
<li>Oppnevne arrangører for årets konferanse.</li>
</ul></p>

<p>Styret er beslutningsdyktig når et flertall av styrets medlemmer er til stede. Vedtak fattes med flertall av de avgitte stemmene. Styreleder har dobbeltstemme ved stemmelikhet.</p>

<br />
<h4>§5.3 Vederlag for styrearbeid</h4>

<p>Styrearbeid lønnes ikke. Direkte kostnader i forbindelse med styrevervet kan dekkes etter skriftlig forhåndsgodkjennelse fra styret</p>

<br />
<h4>§5.4 Signatur</h4>

<p>To styremedlemmer i fellesskap eller styreleder har signaturrett.</p>

<br />
<h4>§6 Valgkomité</h4>

<p>Valgkomitéens oppgave er å foreslå kandidater til styret. Valgkomité velges av årsmøte og skal bestå av minst to personer. Valgkomitéen velges for et år av gangen.</p>

<p>Kandidater som fremmes:
<ul><li>Skal fortrinnvis være arrangører av neste års konferanse  </li>
<li>Skal vektlegges etter kjønnsfordeling, profesjonell tilknytning, erfaring og engasjement i miljøet.</li>
</ul></p>

<br />
<h4>§7 Interessekonflikter</h4>

<p>Styret kan bestemme at styremedlemmer ikke må delta i behandling eller avgjørelse av spørsmål der vedkommende styremedlem har fremtredende personlig eller økonomisk særinteresse i saken.</p>
<p>Ved uforenlige og varige interessekonflikter kan styremedlem utstemmes i ordinært eller ekstraordinært årsmøte før normal periode er utløpt.</p>

<br />
<h4>§8 Endring av vedtekter</h4>

<p>Vedtektene kan besluttes endret av ordinært eller ekstraordinært årsmøte etter å ha vært på sakslisten, og det kreves minst to tredjedels flertall av de avgitte stemmene.</p>

<br />
<h4>§9 Oppløsning</h4>
<p>Oppløsning av foreningen kan bare behandles på ordinært årsmøte. Blir oppløsning vedtatt med minst to tredjedels flertall, innkalles ekstraordinært årsmøte mellom 1 til 3 måneder senere. For at oppløsningen skal skje må vedtaket her gjentas med 2/3 flertall av de avgitte stemmene. Fordeling av foreningens midler besluttes av det til da sittende styre. Ved oppløsning av foreningen skal all gjeld betales.</p>

<p>Sammenslutning med andre interesseorganisasjoner anses ikke som oppløsning av foreningen. Vedtak om sammenslutning og nødvendige vedtektsendringer i tilknytning til dette treffes i samsvar med bestemmelsene om endring av vedtekter, jfr. § 8.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smidigkonferansen</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
        <%= link_to 'Smidigkonferansen', root_url, :class => 'brand' %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to 'Hjem', root_url %></li>
            <li><%= link_to 'Vedtekter', statute_home_path %></li>
            <%= render :partial => 'common/member_menu' %>
          </ul>
         </div><!--/.nav-collapse -->
        <ul class="nav pull-right">
          <%= render :partial => 'common/admin_menu' %>
        </ul>

      </div>
    </div>

  </div>
  <div class="container">
    <%= render :partial => 'common/flashes' %>
    <%= yield %>
    <footer>
      <p>&copy; Smidigkonferansen 2011 - <%= Date.today.year%></p>

    </footer>
  </div><!-- /container -->

</body>
</html>

app/views/members/_email_modal.html.erb
<div class="modal hide" id="<%= themodal %>">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3><%= title %></h3>
  </div>
  <div class="modal-body">
    <p>
      <% persons.each do |p| %>
        "<%= p.name %>" <%= "<#{p.email}>" %>,
      <% end %>
    </p>
  </div>
  <div class="modal-footer">
    <a class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/members/_form.html.erb
<%= simple_form_for(@member, :wrapper => :inline, :html => { :class => 'form-stacked' }) do |f| %>

    <%= f.error_notification %>
    <%= f.input :participate, as: :boolean, :label => "Jeg kommer/kommer ikke" %>
    <%= f.input :email, :label => 'E-postadresse' %>
    <!-- a data-content="We need your email in case we have follow up questions. We respect your privacy and will not share the email address with others." rel="popover" href="#" data-original-title="Email privacy">[?]</a -->
    <%= f.input :name, :label => 'Navn' %>
    <%= f.input :address, :label => 'Adresse' %>
    <%= f.input :postcode, :label => 'Postnr' %>
    <%= f.input :city, :label => 'Sted' %>
    <%= f.input :country, :as => :string, :label => 'Land', :input_html => { :value => 'Norge' } %>
    <%= f.input :password,  :label => 'Passord'%>
    <%= f.input :password_confirmation,  :label => 'Gjenta passord' %>

    <%= f.submit 'Lagre', :class =>'btn primary' %>
  
<% end %>

app/views/members/edit.html.erb
<h3>Editing member</h3>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Medlemmer</h1>

<p>
<%= link_to 'Invitér nytt medlem', new_member_path, :class => 'btn btn-primary' %>
</p>


<p>
  Antall <a data-toggle="modal" href="#membersModal">medlemmer</a>: <%= @members.count %>
  <br/>
  Antall <a data-toggle="modal" href="#participantsModal">påmeldte</a>: <%= @participants.count %>
  <br/>
  Antall inviterte: <%= @invited_count %>
</p>
<%= render partial: 'email_modal', locals: {themodal: 'membersModal', persons: @members, title: "Foreningens medlemmer"} %>
<%= render partial: 'email_modal', locals: {themodal: 'participantsModal', persons: @participants, title: "Påmeldte til genfors 20.mars" } %>

<h2> Medlemmer medlemmer </h2>
<table class="table table-condensed">
  <thead>
  <tr>
    <th>Påmeldt</th>
    <th>Navn</th>
    <th>Epost</th>
    <th>Postnr</th>
    <th>Sted</th>
    <th>Land</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
<% @members.each do |member| %>
  <tr>
    <td><%= member.participate ? "JA" : "Nei" %></td>
    <td><%= member.name %></td>
    <td><%= member.email %></td>

    <td><%= member.postcode %></td>
    <td><%= member.city %></td>
    <td><%= member.country %></td>
    <td><%= link_to 'Show', member, :class => 'btn success' %></td>
    <td><%= link_to 'Destroy', member, confirm: 'Are you sure?', method: :delete, :class => 'btn danger'  %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

app/views/members/new.html.erb
<h3>Masseinvitasjoner til Smidigkonferansen</h3>

<%= form_for "MassInvite",  :url => members_path, :html => {:method => :post} do |f| %>

    <p></p>
  <p>Lim inn eposter og navn under. Vi skiller deltaker på linjeskift og epost og navn på komma, slik:</p>
  <p>oma@example.com, Ole Morten Heggebakken Amundsen<br/>
  kja@example.com, Knut Johannes Dahle</p>
  <p></p>
  <p><%= f.text_area :emails, class: 'input-xxlarge' %></p>

  <p><%= f.submit "Send invitasjon til alle" %></p>
<% end %>

app/views/members/show.html.erb
<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Address:</b>
  <%= @member.address %>
</p>

<p>
  <b>Postcode:</b>
  <%= @member.postcode %>
</p>

<p>
  <b>City:</b>
  <%= @member.city %>
</p>

<p>
  <b>Country:</b>
  <%= @member.country %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>